### ISSUE TITLE
[2.0] Cannot transform tag into dictionary

### ISSUE THREAD

**Issue by haplo** [tinytag/tinytag#219]
**Describe the bug**
TinyTag 2.0 fails to transform tags into a dictionary.

**To Reproduce**

```python
>>> tag = TinyTag.get(file_path)
>>> dict(tag)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
TypeError: '_Ogg' object is not iterable
>>> tag.as_dict()
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
AttributeError: '_Ogg' object has no attribute 'as_dict'. Did you mean: '_as_dict'?
>>> tag._as_dict()
{'filename': '/home/fidel/Music/Blind Guardian/1995 - Imaginations From the Other Side/01 - Imaginations From the Other Side.opus', 'filesize': 7472278, 'duration': 439.2998125, 'channels': 2, 'bitrate': None, 'bitdepth': None, 'samplerate': 48000, 'artist': 'Blind Guardian', 'albumartist': 'Blind Guardian', 'composer': None, 'album': 'Imaginations From the Other Side', 'disc': 1, 'disc_total': 1, 'title': 'Imaginations From the Other Side', 'track': 1, 'track_total': 12, 'genre': 'Power Metal', 'year': '2007-06-15', 'comment': None, 'extra': {'acoustid_id': '812d49a5-2b37-4b07-b2bd-2d38cbe0bba1', 'albumartistsort': 'Blind Guardian', 'artistsort': 'Blind Guardian', 'asin': 'B000PMG9S0', 'barcode': '094639651726', 'catalog_number': '0946 3 96517 2 6', 'fmps_playcount': '1', 'fmps_rating': '1', 'fmps_rating_amarok_score': '0.5', 'isrc': 'DED831701011', 'label': 'Virgin', 'musicbrainz_albumartistid': '7fa7fc04-1011-4876-8095-ecd232edea87', 'musicbrainz_albumid': '7ea40f26-ce19-48ba-8601-e279394ec063', 'musicbrainz_artistid': '7fa7fc04-1011-4876-8095-ecd232edea87', 'musicbrainz_releasegroupid': 'e0fb41f5-17b2-32e0-ad8c-de40f2a6ed4e', 'musicbrainz_releasetrackid': '7f4d2e02-3f65-3d99-8e40-1b376b10f1e5', 'musicbrainz_trackid': '61020907-1a0a-4e95-a0cf-cf96e51ea6c8', 'original_date': '1995-04-05', 'original_year': '1995', 'releasecountry': 'DE', 'releasestatus': 'official', 'releasetype': 'album', 'script': 'Latn'}, 'images': {'front_cover': [], 'back_cover': [], 'leaflet': [], 'media': [], 'other': [], 'extra': {}}}
```

**Expected behavior**
`as_dict` doesn't work [as documented](https://github.com/mathiascode/tinytag/blob/c14db6621cdcfd63301e8b763b0ceede307ffb52/README.md#all-metadata). `_as_dict` exists and does work, but being a private method I'm not comfortable calling it.

I would like to see `dict(tag)` to work too, more Pythonic IMO and it could call `as_dict` underneath.

**Sample file**
Will provide if necessary, but this seems to happen for any tag.

**Comment by haplo** [comment]
Oh, my bad, I got it from mathiascode/tinytag, which is behind upstream. tinytag/tinytag works as expected. :+1:
